### ISSUE TITLE
Why not json_encode()?

### ISSUE THREAD

**Issue by adrianmiu** [bradcornford/Googlitics#4]
Instead of these lines: https://github.com/bradcornford/Googlitics/blob/644368a76703ce27bebd91e51eb6e77ec3eafdac/src/Cornford/Googlitics/AnalyticsBase.php#L371-L373

Seems it's exactly what `json_encode()` does.

**Comment by bradcornford** [comment]
I've pushed an update to the package to cover this in current version 2.5.0.
